### ISSUE TITLE
Suspected Bug in Test Harness

### ISSUE THREAD

**Issue by homestar9** [coldbox-modules/module-template#7]
I'm still trying to figure out how to use this module-template to create and test a custom module, but I'm fairly sure that there's a bug in `/test-harness/application.cfc` line 43:
```
moduleRootPath 	= REReplaceNoCase( this.mappings[ "/root" ], "#request.MODULE_PATH#(\\|/)test-harness(\\|/)", "" );
```
`request.MODULE_PATH` isn't defined anywhere in the template.

**Comment by lmajano** [comment]
Yes, fixed
